env:
  node: true

ignorePatterns:
  - dist
  - template

plugins:
  - jest

extends:
  - plugin:@foxglove/base

overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - plugin:@foxglove/typescript
    parserOptions:
      project: ./tsconfig.json
